---
- name: Install Apache Web Server
  hosts: linux_servers
  become: yes

  tasks:

    - name: Print OS Family
      debug:
        var: ansible_os_family

    - name: Install Apache for RedHat
      yum:
        name: httpd
        state: latest
      when: ansible_os_family=="RedHat"

    - name: Install Apache for Ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_os_family=="Debian"

#    - name: Copy website
#      copy:
#        src: /root/project/index.html
#        dest: /var/www/html
#      notify: Restart Apache

    - name: Start Apache and enable autoboot (RedHat)
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat"

    - name: Start Apache and enable autoboot (Ubuntu)
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family=="Debian"

    - name: Open port 80 ans restart firewall
      shell: firewall-cmd --permanent --add-service=http && firewall-cmd --reload
      when: ansible_os_family=="RedHat"

  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
      when: ansible_os_family=="RedHat"

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
      when: ansible_os_family=="Debian"
