---
- name: Install Apache Web Server
  hosts: linux_servers
  become: yes

  tasks:

    - name: Print OS Family
      debug:
        var: ansible_os_family

    - block: #====== Block for RedHat ======

        - name: Install Apache for RedHat
          yum:
            name: httpd
            state: latest

        - name: Copy website
          copy:
            src: /root/project/index.html
            dest: /var/www/html
          notify: Restart Apache RedHat

        - name: Start Apache and enable autoboot (RedHat)
          service:
            name: httpd
            state: started
            enabled: yes

        - name: Open port 80 ans restart firewall
          shell: firewall-cmd --permanent --add-service=http && firewall-cmd --reload

      when: ansible_os_family=="RedHat"

    - block: #====== Block for Debian======
 
        - name: Install Apache for Ubuntu
          apt:
            name: apache2
            state: latest

        - name: Copy website
          copy:
            src: /root/project/index.html
            dest: /var/www/html
          notify: Restart Apache Debian

        - name: Start Apache and enable autoboot (Ubuntu)
          service:
            name: apache2
            state: started
            enabled: yes

      when: ansible_os_family=="Debian"

  handlers:

    - name: Restart Apache RedHat
      service:
        name: httpd
        state: restarted

    - name: Restart Apache Debian
      service:
        name: apache2
        state: restarted
