---
# При запуске плейбука необходимо указать переменную необходимой вам версии Mikrotik CHR путем добавления значения (номера версии) переменной в команду вызова (-e "version=Номер_версии_CHR")
# Например: ansible-playbook -e "version=7.11.2" microtik_chr.yml
# В inventory файле hosts нужно добавить группу [target_host] с IP целевого хоста

- name: Installing mikrotik CHR
  hosts: target_host
  become: yes

  tasks:
    - name: Ping
      ping:

    - name: Print OS Family
      debug:
        var: ansible_os_family

    - name: Updating repos for CentOS
      yum:
        update_cache: yes
      when: ansible_os_family=="RedHat"

    - name: Updating repos for Ubuntu
      apt:
        update_cache: yes
      when: ansible_os_family=="Debian"

    - name: Installing Unzip for CentOS
      yum:
        name: unzip
        state: latest
      when: ansible_os_family=="RedHat"

    - name: Installing Unzip for Ubuntu
      apt:
        name: unzip
        state: latest
      when: ansible_os_family=="Debian"

    - name: Downloading CHR image
      get_url:
        url: https://download.mikrotik.com/routeros/{{version}}/chr-{{version}}.img.zip
        dest: ./

    - name: Extracting img
      unarchive:
        remote_src: yes
        src: chr-{{version}}.img.zip
        dest: ./

    - name: Writing img on disk
      command: dd if=chr-{{version}}.img of=/dev/sda bs=4M oflag=sync

    - name: Rebooting 1
      command: echo 1 > /proc/sys/kernel/sysrq

    - name: Rebooting 2
      command: echo b > /proc/sysrq-trigger

    - name: Rebooting 3
      command: shutdown -r -t 10
