---
# При запуске плейбука необходимо указать переменную необходимой вам версии Mikrotik CHR путем добавления значения (номера версии) переменной в команду вызова
# Например: ansible-playbook -e "version=номер_версии" microtik_chr.yml

- name: Installing mikrotik CHR
  hosts: target3
  become: yes

  tasks:
    - name: Ping
      ping:

    - name: Updating repos
      dnf:
        update_cache: latest

    - name: Installing Unzip
      yum:
        name: unzip
        state: latest

    - name: Downloading CHR image
      get_url:
        url: https://download.mikrotik.com/routeros/7.11.2/chr-7.11.2.img.zip

    - name: Extracting img
      unarchive:
        src: unzip chr-7.11.2.img.zip
        dest: ./

    - name: Writing img on disk
      command: dd if=chr-7.11.2.img of=/dev/sda bs=4M oflag=sync

    - name: Rebooting 1
      command: echo 1 > /proc/sys/kernel/sysrq

    - name: Rebooting 2
      command: echo b > /proc/sysrq-trigger

    - name: Reebot
      command: reboot
